CREATE TABLE public.schedule (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date        DATE    NOT NULL,
  id_movie    INTEGER NOT NULL,
  id_cinema   INTEGER NOT NULL,
  id_location INTEGER NOT NULL,
  id_time     INTEGER NOT NULL,
  update_at   TIMESTAMP,
  delete_at   TIMESTAMP,
  CONSTRAINT fk_id_movie_showing  FOREIGN KEY (id_movie)    REFERENCES public.movies (id),
  CONSTRAINT fk_id_cinema         FOREIGN KEY (id_cinema)   REFERENCES public.cinema (id),
  CONSTRAINT fk_id_location       FOREIGN KEY (id_location) REFERENCES public.location (id),
  CONSTRAINT fk_id_time           FOREIGN KEY (id_time)     REFERENCES public.time (id)
);