CREATE TABLE public.movies (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         VARCHAR(255)  NOT NULL UNIQUE,
  poster        VARCHAR(255)  NULL,
  backdrop      VARCHAR(255)  NULL,
  release_date  DATE          NOT NULL,
  duration      INTEGER       NOT NULL,
  synopsis      VARCHAR(255)  NOT NULL,
  rating        FLOAT         DEFAULT 0.0,
  id_director   INTEGER       NOT NULL,
  popularity    FLOAT,
  create_at     TIMESTAMP,
  update_at     TIMESTAMP,
  delete_at     TIMESTAMP,
  CONSTRAINT fk_id_director FOREIGN KEY (id_director) REFERENCES public.directors (id)
);