CREATE TABLE public.orders (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ispaid            BOOLEAN,
  total_price       FLOAT        NOT NULL,
  qrcode            VARCHAR(255) NOT NULL,
  name              VARCHAR(255) NOT NULL,
  email             VARCHAR(255) NOT NULL,
  phone             VARCHAR(255) NOT NULL,
  id_schedule       INTEGER      NOT NULL,
  id_payment_method INTEGER      NOT NULL,
  id_user           INTEGER,
  update_at         TIMESTAMP,
  CONSTRAINT fk_id_schedule        FOREIGN KEY (id_schedule)       REFERENCES public.schedule (id),
  CONSTRAINT fk_id_payment_method FOREIGN KEY (id_payment_method) REFERENCES public.payment_method (id),
  CONSTRAINT fk_id_user_order     FOREIGN KEY (id_user)           REFERENCES public.users (id)
);
