INSERT INTO public.directors (id,name) VALUES
	 (1,'Haruo Sotozaki'),
	 (2,'Rich Lee'),
	 (3,'David Fincher'),
	 (4,'James Wan'),
	 (5,'David Leitch'),
	 (6,'Tsui Hark'),
	 (7,'Darrell Smith'),
	 (8,'Kera Dacy'),
	 (9,'Akiva Schaffer'),
	 (10,'Juliette Marguenaud');
INSERT INTO public.directors (id,name) VALUES
	 (11,'Joseph Kosinski'),
	 (12,'Mikael Håfström'),
	 (13,'Steven Spielberg'),
	 (14,'Rebecca Sheridan'),
	 (15,'Chris Appelhans'),
	 (16,'Dean DeBlois'),
	 (17,'Michael Shanks'),
	 (18,'Pierre Perifel'),
	 (19,'Michael Damian'),
	 (20,'Rob Cohen');
INSERT INTO public.directors (id,name) VALUES
	 (21,'MJ Bassett'),
	 (22,'Milos Milicevic'),
	 (23,'Spike Lee'),
	 (24,'Matt Shakman'),
	 (25,'Cheng Siyi'),
	 (26,'Dean Fleischer Camp'),
	 (27,'Stefan Colson'),
	 (28,'Albert Cho'),
	 (29,'John R. Saunders'),
	 (30,'Roman Perez Jr.');
INSERT INTO public.directors (id,name) VALUES
	 (31,'G.B. Sampedro'),
	 (32,'Nisha Ganatra'),
	 (33,'Gaby Smiths'),
	 (34,'Francis Lawrence'),
	 (35,'John Schmidt'),
	 (36,'Omar Deroca'),
	 (37,'Yang Yu'),
	 (38,'Hamish Gough'),
	 (39,'Caitlin Cronenberg'),
	 (40,'Emily Perowne');
INSERT INTO public.directors (id,name) VALUES
	 (41,'Pete Docter'),
	 (42,'Adam B. Stein'),
	 (43,'Amy Lauritsen'),
	 (44,'Tomasz Wiński'),
	 (45,'Lee Dong-Joon'),
	 (46,'Mark Gravas'),
	 (47,'Sherry Hormann'),
	 (48,'Christopher Nolan'),
	 (49,'Thomas J. Churchill'),
	 (50,'William Kaufman');
INSERT INTO public.directors (id,name) VALUES
	 (51,'Florine Nüesch'),
	 (52,'Michael Philippou'),
	 (53,'Emilie Blichfeldt'),
	 (54,'Wisit Sasanatieng'),
	 (55,'Jonathan Entwistle'),
	 (56,'Ram Narayan'),
	 (57,'Jake Schreier'),
	 (58,'Domingo González'),
	 (59,'Luc Besson'),
	 (60,'Vishal Furia');
INSERT INTO public.directors (id,name) VALUES
	 (61,'Namkoong Sun'),
	 (62,'Daphne Esplana'),
	 (63,'Danny Boyle'),
	 (64,'Laura Piani'),
	 (65,'Xiang Qiuliang'),
	 (66,'Rosario Pucciarelli'),
	 (67,'Matthew Fifer'),
	 (68,'Wuershan'),
	 (69,'Jason Hand'),
	 (70,'Isao Hayashi');
INSERT INTO public.directors (id,name) VALUES
	 (71,'Tim Story'),
	 (72,'Jared Hess'),
	 (73,'Skye Borgman'),
	 (74,'Paul Barry'),
	 (75,'Shawn Levy'),
	 (76,'Shigeyuki Miya'),
	 (77,'Ahmad Saleh'),
	 (78,'David Mackenzie'),
	 (79,'Simon Curtis'),
	 (80,'Nick Stergiopoulos');
INSERT INTO public.directors (id,name) VALUES
	 (81,'Nick Hamm'),
	 (82,'Lawrence Fowler'),
	 (83,'Chris Columbus'),
	 (84,'David Midell'),
	 (85,'Calvin Morie McCarthy'),
	 (86,'Gualtiero Jacopetti'),
	 (87,'David Ayer'),
	 (88,'Dean McKendrick'),
	 (89,'Om Raut'),
	 (90,'Rebecca King');
INSERT INTO public.directors (id,name) VALUES
	 (91,'Tom Edmondson'),
	 (92,'Scott Derrickson'),
	 (93,'Ignacio Estaregui'),
	 (94,'Álex de la Iglesia'),
	 (95,'R. Eric Braun'),
	 (96,'Athiyan Athirai'),
	 (97,'Kevin Kumar'),
	 (98,'Dani Girdwood'),
	 (99,'Brad Bird'),
	 (100,'Frank Darabont');
INSERT INTO public.directors (id,name) VALUES
	 (101,'James Wootton'),
	 (102,'Jeff Fowler'),
	 (103,'Lee Unkrich'),
	 (104,'Çağrı Vila Lostuvalı'),
	 (105,'Mike Mitchell'),
	 (106,'Simon West'),
	 (107,'Lasse Hallström'),
	 (108,'Ilya Naishuller'),
	 (109,'Paul Schneider'),
	 (110,'Kelsey Mann');
INSERT INTO public.directors (id,name) VALUES
	 (111,'Gavin O''Connor'),
	 (112,'Jean-Nicolas Bertouille-Blais'),
	 (113,'Mohit Suri'),
	 (114,'Peter Jackson'),
	 (115,'Kurtis David Harder'),
	 (116,'Martin Scorsese'),
	 (117,'Drew Hancock'),
	 (118,'Norberto López Amado'),
	 (119,'James Hawes'),
	 (120,'Vinicius Coimbra');
INSERT INTO public.directors (id,name) VALUES
	 (121,'Sean Byrne'),
	 (122,'Justin Lin'),
	 (123,'Bobby Bonifacio'),
	 (124,'Francis Ford Coppola'),
	 (125,'Stanislav Govorukhin'),
	 (126,'Julius Onah'),
	 (127,'Anne Juin'),
	 (128,'William Stead'),
	 (129,'Adam Somner'),
	 (130,'Tommy Wirkola');
INSERT INTO public.directors (id,name) VALUES
	 (131,'Ali Zamani'),
	 (132,'Noboru Mitsusawa'),
	 (133,'Martin Kulhawy'),
	 (134,'H.H. Cooper'),
	 (135,'Fede Álvarez'),
	 (136,'Simon Cellan Jones'),
	 (137,'Sean Baker'),
	 (138,'Hayao Miyazaki'),
	 (139,'Iain Morris'),
	 (140,'Seong-Young Kim');
INSERT INTO public.directors (id,name) VALUES
	 (141,'Adam Shankman'),
	 (142,'Hideo Nakata'),
	 (143,'Chris Sanders'),
	 (144,'Kyle Newacheck'),
	 (145,'James Cameron'),
	 (146,'Jeff Shiffman'),
	 (147,'Seth Worley'),
	 (148,'Robert Zemeckis'),
	 (149,'Kogonada'),
	 (150,'Sam Raimi');
INSERT INTO public.directors (id,name) VALUES
	 (151,'Darren Aronofsky'),
	 (152,'Paul W. S. Anderson'),
	 (153,'Robin Mishkin Abrams'),
	 (154,'Ari Aster'),
	 (155,'Steven Lisberger'),
	 (156,'Claude Guillouard'),
	 (157,'Justin Tipping'),
	 (158,'Bobbito Garcia'),
	 (159,'Oliver Laxe'),
	 (160,'Genki Kawamura');
INSERT INTO public.directors (id,name) VALUES
	 (161,'Hideki Futamura'),
	 (162,'Benny Safdie'),
	 (163,'Alejandro Valbuena'),
	 (164,'Lloyd Kaufman'),
	 (165,'Tatsuya Yoshihara'),
	 (166,'Nimród Antal'),
	 (167,'Brad Furman'),
	 (168,'Brian Kirk'),
	 (169,'Wong Kar-Wai'),
	 (170,'James Grayford');
INSERT INTO public.directors (id,name) VALUES
	 (171,'Tom Bancroft'),
	 (172,'Alexander Tucker'),
	 (173,'William Eubank'),
	 (174,'Nick Simon'),
	 (175,'Silvio Soldini'),
	 (176,'Mugil'),
	 (177,'Dan Allen'),
	 (178,'Barry Jenkins'),
	 (179,'Renny Harlin'),
	 (180,'Russell Mulcahy');
INSERT INTO public.directors (id,name) VALUES
	 (181,'Katsuya Shigehara'),
	 (182,'Kaouther Ben Hania'),
	 (183,'Edgar Wright'),
	 (184,'Joachim Trier'),
	 (185,'Ryan Crego'),
	 (186,'Ben Leonberg'),
	 (187,'Bryan M. Ferguson'),
	 (188,'Stewart Hamilton'),
	 (189,'Park Chan-wook'),
	 (190,'Walter Salles');
INSERT INTO public.directors (id,name) VALUES
	 (191,'Jim Sharman'),
	 (192,'Jan Ole Gerster'),
	 (193,'Chiu Lo-Kong'),
	 (194,'Martin Bourboulon'),
	 (195,'Cori Glazer'),
	 (196,'Bryce McGuire'),
	 (197,'Bryan Singer'),
	 (198,'Moritz Mohr'),
	 (199,'Sujeeth'),
	 (200,'Hadrah Daeng Ratu');
INSERT INTO public.directors (id,name) VALUES
	 (201,'Amélie Bonnin'),
	 (202,'Benoît Daffis'),
	 (203,'Mamoru Oshii'),
	 (204,'Benny Kung'),
	 (205,'Kiah Roache-Turner'),
	 (206,'Steven M. Smith'),
	 (207,'Mamoru Hosoda'),
	 (208,'Thomas Pistor Eisenman'),
	 (209,'Jane Schoenbrun'),
	 (210,'Juno Mak');
INSERT INTO public.directors (id,name) VALUES
	 (211,'Yoshiyuki Okuyama'),
	 (212,'Kevin Z. Alambra'),
	 (213,'Katsuhide Motoki'),
	 (214,'Ben Smallbone'),
	 (215,'Derek Cianfrance'),
	 (216,'Cédric Klapisch'),
	 (217,'Shinobu Yaguchi'),
	 (218,'Steven Feinartz'),
	 (219,'Scott B. Hansen'),
	 (220,'Dhrubo Banerjee');
INSERT INTO public.directors (id,name) VALUES
	 (221,'Claude Zidi Jr.'),
	 (222,'Till Endemann'),
	 (223,'Peter Mettler'),
	 (224,'Luca Guadagnino'),
	 (225,'Bill Guttentag'),
	 (226,'Chris Stuckmann'),
	 (227,'Urška Djukić'),
	 (228,'James Marquand'),
	 (229,'Cherien Dabis'),
	 (230,'Eva Libertad');
INSERT INTO public.directors (id,name) VALUES
	 (231,'Lynne Ramsay'),
	 (232,'Melkior Serdarevic'),
	 (233,'Simon Stone'),
	 (234,'Julia Ducournau'),
	 (235,'Lilli-Marie Schopp'),
	 (236,'Cédric Jimenez'),
	 (237,'Kate Woods'),
	 (238,'Yannis Zafeiriou'),
	 (239,'Boyapati Srinu'),
	 (240,'Amanda M. Benchley');
INSERT INTO public.directors (id,name) VALUES
	 (241,'Marco Manetti'),
	 (242,'Atena Assiaee'),
	 (243,'Agustín Díaz Yanes'),
	 (244,'Santiago Fernández Calvete'),
	 (245,'Vladimír Borský'),
	 (246,'Radu Jude'),
	 (247,'Ridley Scott'),
	 (248,'Leonardo Van Dijl'),
	 (249,'Jason Wright'),
	 (250,'Chris Tex');
INSERT INTO public.directors (id,name) VALUES
	 (251,'Kenji Iwaisawa'),
	 (252,'Bi Gan'),
	 (253,'Anastasiya Biryukova'),
	 (254,'Antonio Capuano'),
	 (255,'Luis Quijano'),
	 (256,'Sean Donohue'),
	 (257,'Ema Ryan Yamazaki'),
	 (258,'Ulrich Köhler'),
	 (259,'Byun Sung-hyun'),
	 (260,'Jafar Panahi');
INSERT INTO public.directors (id,name) VALUES
	 (261,'Tsuyoshi Inoue'),
	 (262,'Asier Altuna'),
	 (263,'Federico Fellini'),
	 (264,'Aitor Arregi'),
	 (265,'Kei Ishikawa'),
	 (266,'John McPhail'),
	 (267,'Péter Soós'),
	 (268,'Emma James'),
	 (269,'Liam Calvert'),
	 (270,'Simon Rooke');
INSERT INTO public.directors (id,name) VALUES
	 (271,'Hideaki Anno'),
	 (272,'Dietmar Post'),
	 (273,'Michael Dweck'),
	 (274,'Cha Jeong-yoon'),
	 (275,'Myrid Carten');
